const ERROR_KEYS = {
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_EMAIL_IN_USE: "AUTH_EMAIL_IN_USE",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_FORGOT_PASSWORD_CODE_USER_NOT_FOUND:
    "AUTH_FORGOT_PASSWORD_CODE_USER_NOT_FOUND",
  PRUEBA_TREE_NOT_FOUND: "ID_TREE_NOT_FOUND"
};

export default ERROR_KEYS;
